CREATE TABLE `booking_service` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `booking_id` bigint NOT NULL,
  `service_id` bigint NOT NULL,
  `shop_service_id` bigint NOT NULL,
  `assigned_staff_id` bigint DEFAULT NULL,
  `assigned_at` datetime DEFAULT NULL,
  `display_order` int NOT NULL,
  `service_price` decimal(10,2) NOT NULL,
  `estimated_duration` int NOT NULL COMMENT 'Duration in minutes',
  `service_status` varchar(20) DEFAULT 'PENDING',
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_bs_booking` (`booking_id`),
  KEY `fk_bs_service` (`service_id`),
  KEY `fk_bs_shop_service` (`shop_service_id`),
  KEY `fk_booking_service_staff` (`assigned_staff_id`),
  CONSTRAINT `fk_booking_service_staff` FOREIGN KEY (`assigned_staff_id`) REFERENCES `staff` (`id`),
  CONSTRAINT `fk_bs_booking` FOREIGN KEY (`booking_id`) REFERENCES `booking` (`id`),
  CONSTRAINT `fk_bs_service` FOREIGN KEY (`service_id`) REFERENCES `service` (`id`),
  CONSTRAINT `fk_bs_shop_service` FOREIGN KEY (`shop_service_id`) REFERENCES `shop_service` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
