CREATE TABLE `booking` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `booking_number` varchar(20) NOT NULL,
  `customer_id` bigint NOT NULL,
  `vehicle_id` bigint NOT NULL,
  `shop_id` bigint NOT NULL,
  `booking_type` varchar(20) NOT NULL,
  `scheduled_datetime` datetime NOT NULL,
  `token_number` int DEFAULT NULL,
  `booking_status` varchar(20) DEFAULT 'PENDING',
  `arrival_time` datetime DEFAULT NULL,
  `otp_hash` varchar(255) DEFAULT NULL,
  `otp_verified` tinyint(1) DEFAULT '0',
  `otp_verified_at` datetime DEFAULT NULL,
  `accepted_at` datetime DEFAULT NULL,
  `estimated_completion_time` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `payment_status` varchar(20) DEFAULT 'PENDING',
  `cancelled_by` varchar(20) DEFAULT NULL,
  `cancellation_reason` text,
  `notes` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `booking_number` (`booking_number`),
  KEY `fk_booking_customer` (`customer_id`),
  KEY `fk_booking_vehicle` (`vehicle_id`),
  KEY `fk_booking_shop` (`shop_id`),
  CONSTRAINT `fk_booking_customer` FOREIGN KEY (`customer_id`) REFERENCES `user` (`id`),
  CONSTRAINT `fk_booking_shop` FOREIGN KEY (`shop_id`) REFERENCES `shop` (`id`),
  CONSTRAINT `fk_booking_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
